spring:
  application:
    name: asrevocast
  cloud:
    kubernetes:
      config:
        sources:
        - name: ${spring.application.name}
        - name: default
    stream:
      bindings:
        input:
          destination: asrevo.new.rtp.pkt
          group: ${random.uuid}
          contentType: application/octet-stream
      rabbit:
        bindings:
          input:
            consumer:
              exchangeType: fanout
              durableSubscription: false
              acknowledgeMode: NONE