spring:
  rabbitmq:
    username: rabbit
    password: RxxFqNGpScRe
    host: rabbitmq-1-rabbitmq-discovery
    virtual-host: rabbit
  cloud:
    stream:
      bindings:
        input:
          destination: asrevo.new.rtp.pkt
          group: ${random.uuid}
      rabbit:
        bindings:
          input:
            consumer:
              exchangeType: fanout
              durableSubscription: false
              acknowledgeMode: NONE