spring:
  application:
    name: pipeline
  cloud:
    kubernetes:
      config:
        sources:
        - name: ${spring.application.name}
        - name: default
    stream:
      bindings:
        output:
          destination: asrevo.new.rtp.pkt
          contentType: application/octet-stream
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: fanout
              durableSubscription: false
              acknowledgeMode: NONE