spring:
  rabbitmq:
    username: nwxkdlml
    password: cd9LnYXkcVzbzrBSYCDixZD3howw_k-O
    host: rhino.rmq.cloudamqp.com
    virtual-host: nwxkdlml
  cloud:
    stream:
      bindings:
        output:
          destination: asrevo.new.rtp.pkt
          contentType: application/octet-stream
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: fanout
              durableSubscription: false
              acknowledgeMode: NONE